name: python tests

on: [push]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.8.4'
        - run: pip install -r requirements.txt
        - run: pytest
